services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: banking-intent-classifier

    ports:
      - "8000:8000"

    volumes:
      - ./logs:/app/logs

    env_file:
      - .env

    restart: unless-stopped